### ISSUE TITLE
experiment-launcher

### ISSUE THREAD

**Issue by sverhoeven** [NLeSC/TEAM2018#15]
A webservice to generate and launch a Jupyter notebook.

See https://github.com/eWaterCycle/experiment-launcher

**Comment by sverhoeven** [comment]
@nielsdrost quoted: It is wizard for a notebook

**Comment by nielsdrost** [comment]
Great idea. Should also include the "bigger picture" in the paper, including the explorer that calls the generator service.

**Comment by romulogoncalves** [comment]
@sverhoeven @nielsdrost who could lead this paper?
You are already involved in #13 and #18 papers.

**Comment by romulogoncalves** [comment]
@sverhoeven @nielsdrost could we merge this paper with #13? If yes, and since Niels has a nice view of the "bigger picture", I would say Niels would lead the writing of such paper and we would move #18 grpc-bmi-containers to another session.

What do you think?

**Comment by romulogoncalves** [comment]
@sverhoeven were all the goals achieved? Could you summarize in 3 lines what was achieved? Can we consider it done and close this issue?

**Comment by romulogoncalves** [comment]
@sverhoeven what is the current status?

**Comment by sverhoeven** [comment]
An abstract was submitted to EGU 2019 conference.

**Comment by romulogoncalves** [comment]
Excellent.
