### ISSUE TITLE
QMFlows: Automatic Workflow in quantum Chemistry

### ISSUE THREAD

**Issue by felipeZ** [NLeSC/TEAM2018#25]
**Title**: QMFlows: Automatic Workflow in quantum Chemistry

**Editor**: Felipe Zapata

**about**: This library tackles the construction and efficient execution of computational chemistry workflows

**Comment by romulogoncalves** [comment]
@felipeZ will you be at the Sprint? In the list of participants you said `0`, i.e., not joining.

**Comment by felipeZ** [comment]
@romulogoncalves, yes I am participating. I misunderstood the instructions :)

**Comment by felipeZ** [comment]
we will submit the papers in a couple of weeks
