### ISSUE TITLE
Publications from January 2014 until June 2018

### ISSUE THREAD

**Issue by romulogoncalves** [NLeSC/TEAM2018#33]
* We need a list of all publications which are listed in the projects report from January 2014 until June 2018.
* Check if all are in Zotero.
* Check what is in Zotero and not in this list and if it should be there.
* Go after publications which are not listed in the final reports.
* Publications of project which do not have a final report, i.e., either projects for which a report was not created or are still in execution.

**Comment by jmaassen** [comment]
My opinion is that we should add everything, peer reviewed papers, non-peer reviewed papers/abstracts, blogs, tweets, etc. but we should tag it in zotero in such a way that we can filter it later.

**Comment by romulogoncalves** [comment]
For the 4 days of the sprint the people to who this issue is assigned should report hours on:
eStep

Only report the days you were present at the Sprint.

For extra work you need to request time to the tech leads by sending an email to techleads@esciencecenter.nl

**Comment by romulogoncalves** [comment]
@jiskattema could you write down here a little summary about your findings and append the presentation slides you showed to us in the end of the Sprint?

Once you have done it, I will close the issue.
Thanks a lot for the great work.

**Comment by romulogoncalves** [comment]
@jiskattema have we processed all the email about publications? 
Could you add some numbers here about your findings?

**Comment by romulogoncalves** [comment]
All the information should be by now in the evaluation report.
The issue can be closed.
