### ISSUE TITLE
NLeSC social media impact analysis

### ISSUE THREAD

**Issue by romulogoncalves** [NLeSC/TEAM2018#36]
Analyze the impact of the Netherlands eScience Center on Twitter. Create data visualizations showing tweets, retweets, mentions and hastags over time. Link data to relevant events.

**Comment by eriktks** [comment]
Analyze the impact of the Netherlands eScience Center on Twitter. Create data visualizations showing tweets, retweets, mentions and hastags over time. Link data to relevant events.

**Comment by florian-huber** [comment]
Not sure at what stage this project is. But there's quite a lot of open APIs or wrappers such as 
- tweedy (python) https://github.com/tweepy/tweepy 
- twython (python) https://github.com/ryanmcgrath/twython

And also some nice introductions (here an example for twython): https://stackabuse.com/accessing-the-twitter-api-with-python/
(more complete list of options: https://developer.twitter.com/en/docs/developer-utilities/twitter-libraries#python)

**Comment by fdiblen** [comment]
@romulogoncalves @eriktks 
Would be nice to work together during the sprint. Maybe we can create these visualizations together. 
Please see the issue #32

**Comment by romulogoncalves** [comment]
@eriktks could you write down here a little summary about your findings and append the presentation slides you showed to us in the end of the Sprint?

Once you have done it, I will close the issue.
Thanks a lot for the great work.

**Comment by eriktks** [comment]
code and graphs can be found on https://github.com/teamproject2018-09
